services:
  uverl.develop:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        WWWUSER: ${WWWUSER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:5173"
    container_name: uvel-app
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - ".:/var/www/html"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini"
    networks:
      - uvel
    depends_on:
      - db
  db:
    image: mariadb:10.6.18
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "uveldb:/var/lib/mysql"
      - ./database/sqldump:/docker-entrypoint-initdb.d
    networks:
      - uvel
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:80"
    networks:
      - uvel
networks:
  uvel:
    driver: bridge
volumes:
  uveldb:
    driver: local
